### ISSUE TITLE
[rctree] Add WeakRef?

### ISSUE THREAD

**Issue by thelink2012** [SimonSapin/rust-forest#1]
I found myself needing to weakly reference a node and there was no pub type for that so I wonder if I should change my design or it'd be a good idea to add a WeakRef to the library?

**Comment by SimonSapin** [comment]
I could imagine a few ways:
- Add a `downgrade` method on `NodeRef` and something like `pub struct NodeWeak<T>(Weak<RefCell<Node<T>>>);` with an`upgrade` method.
- Make the `NodeRef` field public so that you can do this yourself
- Remove `NodeRef` and expose `Rc` directly. I’m not sure where all the `NodeRef` methods would go, though.

I’d take a PR for any of these, or something else, as you see fit.

**That said**, this repository was kinda meant as a way to explore various approaches and write down my findings, not really to be actually used by other code.

[In Kuchiki](https://github.com/SimonSapin/kuchiki/blob/master/src/tree.rs) for example, I ended up with something a lot like rctree here but with some changes. (`Node::data` is not generic, nodes are not entirely in `RefCell`, …)

I’d recommend copy/pasting the rctree code into your crate and tweak it as you see fit. I made many decisions and assumptions when building it and making different choices is perfectly valid. Different projects are gonna have different requirements, and I don’t really want to try and maintain a library for every kind of tree people might want to use :)

**Comment by thelink2012** [comment]
I see, I'll be copying it into my crate and tweaking it then, indeed may be a better idea.
