### ISSUE TITLE
Tree structure is not enforced

### ISSUE THREAD

**Issue by Columbus240** [SimonSapin/rust-forest#4]
It is possible with rctree to do the following:

```
let root = NodeRef::new(0);
root.append(NodeRef::new(1));
root.last_child().append(root);
```

Which means that this crate does not only acyclic directed graphs (trees), but directed graphs where a node can only have one edge pointing to it but many edges going out. In other words, this crate allows trees to be constructed which are not trees in the usual sense.

It probably is not intended, because it prohibits further use of `root` even if `root.last_child().append(root.clone())` is used.
Maybe the `append()` should panic when it detects a circular reference.

**Comment by Columbus240** [comment]
Self-loops compile, and panic during execution, but could probably also use a better message.

```
let root = NodeRef::new(0);
root.append(root.clone);
```

**Comment by SimonSapin** [comment]
Indeed, allowing cycles (when only considering first child and next sibling edges, otherwise there are many obvious cycles like `x.first_child.parent == x`) is not intended.

`x.append(y)` is intended to move not only y but also it's descendants (overall, the subtree rooted at y). So I _think_ cycles can only be introduced if y is an ancestor of x (or is x). Unfortunately, detecting this take O(n) time (with n = number of ancestors of x) whereas `append` and friends were previously O(1). And since building a tree is usually based on calling `append` repeatedly, that becomes O(average depth × n nodes) instead of O(n nodes). Not quite quadratic, but still significant.

Is checking this in `append` worth the run-time cost?

**Comment by SimonSapin** [comment]
In addition to algorithms not expecting it (the descendants iterator is implemented here would stop too early, another implementation might loop infinitely) creating cycles of first child or next sibling edges cause all nodes in the cycle and their descendants to be leaked unless the cycle is broken manually. (`Rc`’s strong reference count never reaches zero. The parent, last child, and previous sibling edges are `rc::Weak` internally to avoid this for "normal" trees.)

---

For what it’s worth, Python’s ElementTree does not protect against this:

``` python
import xml.etree.ElementTree as ET
import itertools

a = ET.Element('a')
b = ET.Element('b')
a.append(b)
b.append(a)

for elem in itertools.islice(a.iter(), 20):
    print elem.tag,
```

```
a b a b a b a b a b a b a b a b a b a b
```

But lxml does. The same program with `lxml.etree` instead of `xml.etree.ElementTree` raises an exception:

```
Traceback (most recent call last):
  File "a.py", line 8, in <module>
    b.append(a)
  File "src/lxml/lxml.etree.pyx", line 833, in lxml.etree._Element.append (src/lxml/lxml.etree.c:49649)
  File "src/lxml/apihelpers.pxi", line 1278, in lxml.etree._appendChild (src/lxml/lxml.etree.c:28541)
ValueError: cannot append parent to itself
```

The error message says "parent", but the code calls a function called `_isAncestorOrSame` that does what it says.

**Comment by Columbus240** [comment]
It seems to me that both cases are valid. If the tree is unpredictably manipulated, an `append()` should be used that checks `is_ancestor_or_same()`, but if the tree comes from a source that is known to be valid, for example a known-to-be-valid XML file, then `append()` can speed up by not using `is_ancestor_or_same()`.
Would it be a good idea to create a new `unsafe append_unchecked()` and `append()` uses `is_ancestor_or_same()` (and after that calls `append_unchecked()` from an `unsafe` block)? It would have to be documented, but it works.
This solution smells a little, having twice almost the same function.

**Comment by SimonSapin** [comment]
Yeah, that could work.

Regardless, this repository is where I published the results of some experiments, but I don’t intend to maintain it over time. If you’d like to make this code evolve I suggest copying it into your project and starting from there. It’s what I did [in Kuchiki](https://github.com/SimonSapin/kuchiki/blob/master/src/tree.rs) with a more specialized tree data structure.

**Comment by Columbus240** [comment]
I'll create a new repo, and add a reference to you.
